---
title: "RockCreek_Climate_Nov2020"
author: "Simon Marks"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
library(data.table)
library(openair)
```

```{r}

coalesce_join <- function(x, y, 
                          by = NULL, suffix = c(".x", ".y"), 
                          join = dplyr::full_join, ...) {
  
    joined <- join(x, y, by = by, suffix = suffix, ...)
    
    # names of desired output
    cols <- dplyr::union(names(x), names(y))
    
    to_coalesce <- names(joined)[!names(joined) %in% cols]
    
    suffix_used <- suffix[ifelse(endsWith(to_coalesce, suffix[1]), 1, 2)]
    
    # remove suffixes and reduplicate
    to_coalesce <- unique(substr(
        to_coalesce, 
        1, 
        nchar(to_coalesce) - nchar(suffix_used)
    ))
    
    coalesced <- purrr::map_dfc(to_coalesce, ~dplyr::coalesce(
        joined[[paste0(.x, suffix[1])]], 
        joined[[paste0(.x, suffix[2])]]
    ))
    
    names(coalesced) <- to_coalesce
    
    dplyr::bind_cols(joined, coalesced)[cols]
}

```

```{r}

read_atm_hobo_u20 <- function(path){
  
  # Avoid problem of not knowing the number of cols coming from Hobo file (i.e. avoid warning)
  no_of_cols <- readr::read_csv(path, skip = 1, n_max = 1, col_types = cols(.default = col_guess())) %>% 
    ncol()
  
  no_of_cols_drop_at_end <- no_of_cols - 4
  
  data <- readr::read_csv(path, skip = 2, 
                          col_types = paste0("_cdd", stringi::stri_dup("_", no_of_cols_drop_at_end)), 
                          col_names = c("Date", "baro.pressure_psi", "baro.temp_F")) %>% 
    dplyr::mutate(Date = lubridate::mdy_hms(Date)) %>% 
    dplyr::filter(!is.na(baro.pressure_psi))
  
  return(data)
  
}

```

```{r}

## function for reading climate data from raw file- snow or no snow in file (there were two file configurations in the raw data)

read_climate <- function(path){
  
  col_names <- readr::read_lines(path, skip = 1, n_max = 1) %>% 
    stringr::str_remove_all(pattern = '\"') %>% 
    stringr::str_split(pattern = ",") %>% 
    purrr::pluck(1) %>% 
    str_to_lower() %>% 
    str_detect("snow")
  
  if(TRUE %in% col_names){
    
    data <- readr::read_csv(path, skip = 2, 
                            col_types = "_cddddddddd", col_names = c("Date", "solar.rad_1", "solar.rad_2", "wind_speed", "gust_speed",
                                                                     "temp_F", "RH", "rain_in", "snowdepth_in", "current")) %>% 
      dplyr::mutate(Date = lubridate::mdy_hms(Date))
    
    return(data)
    
  } else {
    
    data <- readr::read_csv(path, skip = 2, 
                            col_types = "_cddddd", col_names = c("Date", "solar.rad_1", "wind_speed", "gust_speed", 
                                                                     "temp_F", "RH")) %>% 
      dplyr::mutate(Date = lubridate::mdy_hms(Date))
    
    return(data)
    
  }
  
}
  
```


```{r}

compile_atm_data <- function(path, prev_compile = NULL, written_file_name){
  
  if(!stringr::str_detect(written_file_name, pattern = ".csv")){
    stop("provided written file name must end with .csv")
  }
  
  ## Create char. vector of file names w/ directory path prepended contained in provided path
  
  files <- list.files(path, full.names = TRUE)
  
  ## Creates list of clean/standardized data (data frames) for all those provided in the path using `read_atm_hobo_u20` function
  
  listed_files <- purrr::map(files, read_atm_hobo_u20)
  
  # Keeps files grouped by instrument and orders data chronologically. Duplicate observations are removed.
  compiled <- dplyr::bind_rows(listed_files) %>% 
    dplyr::distinct() %>%
    # `dplyr::arrange` would not function properly here
    do(data.frame(with(data = .,.[order(Date),])))
  
  ## Compiles well data using only those files provided in the path
  
  if(is.null(prev_compile)){
    
    compiled <- compiled %>% 
      dplyr::mutate(Date = as.character(Date))
    
    # Write out compiled file from provided files only 
    readr::write_csv(compiled, path = paste0(path, "/", written_file_name))
    
    ## When prev_compile file is provided, the files provided in the path are appended to the previously compiled file
    # Performs coalescing join- user does not have to worry about feeding in data that has been previously compiled
  } else {
    
    appended_compile <- prev_compile %>%
      coalesce_join(compiled, by = "Date") %>% 
      do(data.frame(with(data = .,.[order(Date),]))) %>%
      dplyr::distinct() %>% 
      purrr::discard(~all(is.na(.))) %>% 
      dplyr::mutate(Date = as.character(Date))
    
    # Write out appended compile file
    readr::write_csv(appended_compile, path = paste0(path, "/", written_file_name))

  }
  
}

```


```{r}

compile_climate_data <- function(path, prev_compile = NULL, written_file_name){
  
  if(!stringr::str_detect(written_file_name, pattern = ".csv")){
    stop("provided written file name must end with .csv")
  }
  
  ## Create char. vector of file names w/ directory path prepended contained in provided path
  
  files <- list.files(path, full.names = TRUE)
  
  ## Creates list of clean/standardized data (data frames) for all those provided in the path using `read_climate` function
  
  listed_files <- purrr::map(files, read_climate)
  
  # Keeps files grouped by instrument and orders data chronologically. Duplicate observations are removed.
  compiled <- dplyr::bind_rows(listed_files) %>% 
    dplyr::distinct() %>%
    # `dplyr::arrange` would not function properly here
    do(data.frame(with(data = .,.[order(Date),])))
  
  ## Compiles well data using only those files provided in the path
  
  if(is.null(prev_compile)){
    
    compiled <- compiled %>% 
      dplyr::mutate(Date = as.character(Date))
    
    # Write out compiled file from provided files only 
    readr::write_csv(compiled, path = paste0(path, "/", written_file_name))
    
    ## When prev_compile file is provided, the files provided in the path are appended to the previously compiled file
    # Performs coalescing join- user does not have to worry about feeding in data that has been previously compiled
  } else {
    
    appended_compile <- prev_compile %>%
      coalesce_join(compiled, by = "Date") %>% 
      do(data.frame(with(data = .,.[order(Date),]))) %>%
      dplyr::distinct() %>% 
      purrr::discard(~all(is.na(.))) %>% 
      dplyr::mutate(Date = as.character(Date))
    
    # Write out appended compile file
    readr::write_csv(appended_compile, path = paste0(path, "/", written_file_name))

  }
  
}

```

## Update Control Climate data with Nov. 2020 download

### Climate Data

```{r}

# previous Control climate compile, Aug 2020
compiled_Control_climate_Aug2020 <- readr::read_csv(file = "Climate_CM_Aug2020/compiled_Climate_Control_Aug2020.csv", 
                                       col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = lubridate::ymd_hms(Date))

compiled_Control_Climate_Nov2020 <- compile_climate_data("Climate_Control_Nov2020", prev_compile = compiled_Control_climate_Aug2020, written_file_name = "compiled_Climate_Control_Nov2020.csv")


```

### Atm Data

```{r}

# previous Control ATM compile, Aug 2020
compiled_Control_ATM_Aug2020 <- readr::read_csv(file = "Atm_CM_Aug2020/compiled_ATM_Control_Aug2020.csv", 
                                       col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = lubridate::ymd_hms(Date))

# recall that the control climate station was down between 2020-07-18 and 2020-08-18, reflected in the combo climate and atm file (below code chunk)
compiled_ATM_Climate_Nov2020 <- compile_atm_data("Atm_Control_Nov2020", prev_compile = compiled_Control_ATM_Aug2020, written_file_name = "compiled_Atm_Control_Nov2020.csv")


```
## Combine Climate and ATM data

```{r}
compiled_ATM_Climate_Control_Nov2020 <- dplyr::left_join(compiled_Control_Climate_Nov2020, compiled_ATM_Climate_Nov2020, by = "Date") 

compiled_ATM_Climate_Control_Nov2020 %>% 
  dplyr::mutate(Date = as.character(Date)) %>% 
  readr::write_csv("Climate_Control_Nov2020/compiled_ATM_Climate_Control_Nov2020.csv")
```

